### ISSUE TITLE
XCode 10 and Swift 4.2 fails to build

### ISSUE THREAD

**Issue by DamascenoRafael** [RedMadRobot/input-mask-ios#51]
The pod does not compile with Xcode 10 and Swift 4.2

**Installation Type**
- Cocoapods

**Additional context**
```
/Users/Damasceno/Documents/GitHub/caronae-ios/Pods/InputMask/Source/InputMask/InputMask/Classes/View/MaskedTextFieldDelegate.swift:167:72: error: 'UITextFieldDidEndEditingReason' has been renamed to 'UITextField.DidEndEditingReason'
    open func textFieldDidEndEditing(_ textField: UITextField, reason: UITextFieldDidEndEditingReason) {
                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                       UITextField.DidEndEditingReason
UIKit.UITextFieldDidEndEditingReason:3:18: note: 'UITextFieldDidEndEditingReason' was obsoleted in Swift 4.2
public typealias UITextFieldDidEndEditingReason = UITextField.DidEndEditingReason
```

**Comment by ultimate-deej** [comment]
As a temporary workaround, open Pods project settings, select InputMask target, and change swift language version to Swift 4. Note that you need to do this every time you run `pod install`.

**Comment by taflanidi** [comment]
I'm going to issue an update today or tomorrow.
Please, stay tuned.
